apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: savesync

resources:
  - namespace.yaml
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: savesync
