apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: savesync-staging

bases:
  - ../../base

commonLabels:
  environment: staging

images:
  - name: registry.axelfrache.me/savesync/backend
    newTag: latest  # CI builds: main, main-<sha>, latest
  - name: registry.axelfrache.me/savesync/frontend
    newTag: latest  # CI builds: main, main-<sha>, latest

patches:
  # Backend: 1 replica (SQLite) avec resources moyennes
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 150m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 192Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 750m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 768Mi
  
  # Frontend: 2 replicas
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  
  # Ingress: domaine staging
  - target:
      kind: Ingress
      name: savesync
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: savesync-staging.axelfrache.com
